### ISSUE TITLE
<Folder Include="Plugins\" /> where is this folder 

### ISSUE THREAD

**Issue by EngAhmedNaeem** [ndmt1at21/Paint#1]

**Comment by ndmt1at21** [comment]
You should build all shape plugin: Circle, Diamond, ... and then copy all the result (.dll file) to Paint/Plugins folder (you should delete BRControll.dll in each built plugin because it can make conflict)

![image](https://user-images.githubusercontent.com/57802912/165956439-274e0c7d-ab06-4741-99ac-c87c7d786045.png)

**Comment by EngAhmedNaeem** [comment]
string[] pluginIDs = _pluginManager.GetPluginIDs();  returned null
![erroe](https://user-images.githubusercontent.com/100135484/166109018-a16fa7d4-4dc6-4172-963a-582ede5e03cf.JPG)

**Comment by EngAhmedNaeem** [comment]
thank you for helping I fixed it and now it's working

**Comment by EngAhmedNaeem** [comment]
how can add pain tool to this app

**Comment by EngAhmedNaeem** [comment]
> You should build all shape plugin: Circle, Diamond, ... and then copy all the result (.dll file) to Paint/Plugins folder (you should delete BRControll.dll in each built plugin because it can make conflict)
> 
> ![image](https://user-images.githubusercontent.com/57802912/165956439-274e0c7d-ab06-4741-99ac-c87c7d786045.png)

**Comment by EngAhmedNaeem** [comment]
How can convert this application from windows Application to class library thanks.

**Comment by EngAhmedNaeem** [comment]
![image](https://user-images.githubusercontent.com/100135484/167317617-00ecea4e-d4fe-42be-bfdf-1c3a40599165.png)
error list (the name "InverseBooleanConverter" does not exist in the namespace "converters="clr-namespace:Paint.Converters"")

**Comment by EngAhmedNaeem** [comment]
I wonder how to convert Target FrameWork from .net 5 to .net framework 4.8?! thanks

**Comment by EngAhmedNaeem** [comment]
How can I solve this problem in the project? Thanks

> ![image](https://user-images.githubusercontent.com/100135484/167317617-00ecea4e-d4fe-42be-bfdf-1c3a40599165.png) error list (the name "InverseBooleanConverter" does not exist in the namespace "converters="clr-namespace:Paint.Converters"")

**Comment by EngAhmedNaeem** [comment]
Hi, I have an error in Adornertemplate, I don't understand why this appears [](url
![error](https://user-images.githubusercontent.com/100135484/171448710-013cd224-c4a3-4180-963b-1b65d77df663.JPG)
)
